name: VaultwardenOnHeroku_Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AUTOBUS_ENABLE: 1
  CREATE_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  DUO_ENABLE: 1
  GIT_HASH: main
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_VERIFIED: 1

jobs:
  update_and_deploy:
    name: Update Vaultwarden app (to latest version or SHA) on Heroku and deploy.
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: stable
        # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run: curl https://cli-assets.heroku.com/install.sh | sh
    - run: sudo apt update && sudo apt install jq openssl -y
    - run: bash vaultwarden_heroku.sh -a $CREATE_APP_NAME -d $DUO_ENABLE -g $GIT_HASH -v $HEROKU_VERIFIED -b $AUTOBUS_ENABLE -t update